### ISSUE TITLE
Proposal: Remove watcher

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#1001]
I propose removing the periodic process "watch" that records tree heads. Recording old tree heads does not aid in the calculation of consistency proofs, since those are calculated by clients using a persisted checkpoint. Recording them also does not mitigate split view attacks, because the process logging the tree heads is the same as the log itself. Witnesses will calculate consistency between a persisted checkpoint and the current, and they do not need to look back at previous checkpoints.

Also, given the job runs periodically, there's no guarantee it'll actually record every tree head, it's just best effort.

It also seems like it stopped recording data Aug 6th 22. I think this might be because we began tearing down an old cluster. I'm fairly certain no one is reading from the bucket, so it should be safe to delete.

Code links: https://github.com/sigstore/rekor/blob/main/cmd/rekor-server/app/watch.go, https://github.com/sigstore/rekor/blob/main/config/watcher.yaml

cc @asraa @dlorenc

**Comment by asraa** [comment]
> because the process logging the tree heads is the same as the log itself. 

I thought this watcher was meant for anyone to spin up?

I guess I can see why it shouldn't live in this repository.

**Comment by Hayden-IO** [comment]
What's the purpose of recording old tree heads? If you want a witness, then you should run rekor-monitor/omniwitness.
