### ISSUE TITLE
Rekor 1.0

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/rekor#1005]
Pre-release is out!
We want to release Rekor 1.0 at 45f17ce35901b0439c468f248b7121de001eb7da to include a change to rekor-cli which wasn't included in the pre-release.

A tracking issue for Rekor 1.0

Items in progress: [GA Blockers](https://github.com/sigstore/rekor/labels/ga_blocker)

- [x] https://github.com/sigstore/rekor/issues/891
- [x] https://github.com/sigstore/rekor/issues/582
- [x] https://github.com/sigstore/rekor/pull/1102

Candidates: [GA Candidates](https://github.com/sigstore/rekor/labels/ga_candidate)
- [x] https://github.com/sigstore/rekor/issues/997
- [x] https://github.com/sigstore/rekor/issues/988
- [x] https://github.com/sigstore/rekor/issues/901
- [x] https://github.com/sigstore/rekor/issues/1021

**Comment by cpanato** [comment]
release https://github.com/sigstore/rekor/releases/tag/v1.0.0
