### ISSUE TITLE
Checkpoint: Should the Origin be the Tree ID?

### ISSUE THREAD

**Issue by asraa** [sigstore/rekor#1010]
**Description**

All Trees use "Rekor" as origin. Should We include the Tree ID or shard ID in the origin/ecosystem? 
https://github.com/sigstore/rekor/blob/547eb3cef9690bc97e73e35eb3bf1f40b18a3504/pkg/util/checkpoint.go#L30

@bobcallaway @priyawadhwa @lkatalin

**Comment by Hayden-IO** [comment]
From https://github.com/transparency-dev/formats/tree/main/log

> <Origin string> should be a unique identifier for the log identity which issued the checkpoint. The exact format of this is left undefined, but examples of types of value to put here are the log's URL, a base64 encoded hash of its public key, etc.

> The presence of this identifier forms part of the log claim, and guards against two logs producing bytewise identical checkpoints.

A shard ID would guard against two logs producing the same checkpoint.
