### ISSUE TITLE
/v1/log/entries/retrieve returns 500 when requesting malformed proposed entries

### ISSUE THREAD

**Issue by var-sdk** [sigstore/rekor#1040]
**Description**

Repros with [tests/rekor.json](https://github.com/sigstore/rekor/blob/main/tests/rekor.json):
```
$ curl -H "Content-Type: application/json" --data "{\"entries\": [$(cat tests/rekor.json)]}"  "https://rekor.sigstore.dev/api/v1/log/entries/retrieve"
```

```
{"code":500,"message":"SHA mismatch: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 != 45c7b11fcbf07dec1694adecd8c5b85770a12a6c8dfdcf2580a2db0c47c31779"}
```

Similar to https://github.com/sigstore/rekor/issues/1027. 

**Version**

**Comment by asraa** [comment]
Seems like https://github.com/sigstore/rekor/blob/4420d1164c6e53180e6eeb693c8865704c21755d/pkg/api/entries.go#L398 should still have been bad request. 

Can add some testing.
