### ISSUE TITLE
[bug] CI harness test is failing

### ISSUE THREAD

**Issue by asraa** [sigstore/rekor#1051]
**Description**

```
=== RUN   TestHarnessGetAllEntriesLogIndex
    harness_test.go:322: {"ActiveTreeSize":14,"TotalTreeSize":14,"RootHash":"f48075eb61a8262bf0e4169f251868e42ede3276b4cf0a238494b66ed8e94bd2","TimestampNanos":1663169263687839964,"TreeID":"9154130894263455123"}
        
    harness_test.go:207: Reading /tmp/rekor_test_harness.WOFxkp/attestations
    harness_test.go:266: IntotoObj matches stored attestation
    harness_test.go:207: Reading /tmp/rekor_test_harness.WOFxkp/attestations
    harness_test.go:266: IntotoObj matches stored attestation
    harness_test.go:207: Reading /tmp/rekor_test_harness.WOFxkp/attestations
    harness_test.go:266: IntotoObj matches stored attestation
    harness_test.go:207: Reading /tmp/rekor_test_harness.WOFxkp/attestations
    harness_test.go:266: IntotoObj matches stored attestation
    harness_test.go:255: intoto implementation for version '0.0.2' not found: unable to locate entry for version 0.0.2
        
    harness_test.go:255: exit status 1
--- FAIL: TestHarnessGetAllEntriesLogIndex (0.16s)

````

I'll take a look

**Version**

**Comment by priyawadhwa** [comment]
I'm on my phone so can't check the logs at the moment, but if this is an old rekor-cli version run against rekor-server >= v0.12.0 this test should be skipped!

The skipping logic might have a bug in it now that 0.12.0 was recently released

**Comment by asraa** [comment]
Yep thank you so much! Exactly, it's an old version of rekor-cli that doesn't handle the v0.0.2 intoto entries.

Thanks!

**Comment by asraa** [comment]
More generally, even if the CLI can't handle it, we should be regression testing old server versions for these API calls, right? I'll see if I can check in on this later, maybe it's already there.

**Comment by priyawadhwa** [comment]
Yah so we currently test the 2 most recent releases and HEAD, with all combos of rekor-cli and rekor-server

We start with the oldest rekor-server and upgrade twice to mimic staging/prod, and run the tests against all 3 versions of rekor-cli. 

Normally we'd want this to be backwards incompatible but rekor-cli 0.12.0 is a breaking change so gotta skip older versions :/

**Comment by asraa** [comment]
Oh, I guess it's not really necessary! I meant that we can still retrieve v0.0.2 entries against server, it's just that the CLI can't parse it. So I mean some test should exist that runs direct HTTP requests with `curl` against recent versions of the server, rather than the CLI. But that's just a test against the server, which runs at pre-submit anyway. It won't regress with old versions of the server.

Sorry if that doesn't make sense! But I think we're both on the same page! Everything's fine :)
