### ISSUE TITLE
release: release a patch for 0.12.1 allowing v0.0.1 intoto entries

### ISSUE THREAD

**Issue by asraa** [sigstore/rekor#1062]
**Description**

Currently 0.12.0 does not allow v0.0.1 intoto entries. However, clients still need to verify rekor entries (and sometimes upload) v0.0.1 entries: we should have a small patch release including this change

https://github.com/sigstore/rekor/commit/a6d36b8028ecdb4c047dde52b29a76b51b058b2f

**Comment by Hayden-IO** [comment]
cc @cpanato

**Comment by var-sdk** [comment]
I'd also like to get f27af357e6831225507ed97524dec78e034fe63f into the release as well so we can accurately measure SLO for GA. Can we cut 0.12.1 from HEAD (or 0.13.0)?

**Comment by cpanato** [comment]
this https://github.com/sigstore/rekor/commit/a6d36b8028ecdb4c047dde52b29a76b51b058b2f is already in 0.12.0

but i do agree we can make a 0.12.1 release

**Comment by asraa** [comment]
Closed, thanks!
https://github.com/sigstore/rekor/releases/tag/v0.12.1
