### ISSUE TITLE
rekor-cli installation through go

### ISSUE THREAD

**Issue by Mohamed-AH** [sigstore/rekor#1084]
**Description**

I tried to install rekor-cli through go on an ubuntu server on killercoda.com using 
"go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest"
but it was not successful, however I was able to do it successfully manually using 
"git clone https://github.com/sigstore/rekor.git rekor-cli
cd rekor-cli
make rekor-cli
cp rekor-cli /usr/local/bin/" 

**Version**

Not Applicable

**Comment by asraa** [comment]
Hi!

What was your reproducing steps and error messages? I can run the go install successfully:
```
$ go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest
```

**Comment by Mohamed-AH** [comment]
I opened an environment on killercoda.com (https://killercoda.com/playgrounds/scenario/ubuntu)
pasted the command
$ go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest
after the execution, rekor-cli returns "command not found"

but if I do the installation manually with the below commands :
"git clone https://github.com/sigstore/rekor.git rekor-cli
cd rekor-cli
make rekor-cli
cp rekor-cli /usr/local/bin/"
rekor installs correctly and rekor-cli works fine.

am i missing some thing.

**Comment by bobcallaway** [comment]
> I opened an environment on killercoda.com (https://killercoda.com/playgrounds/scenario/ubuntu) pasted the command $ go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest after the execution, rekor-cli returns "command not found"
> 
> but if I do the installation manually with the below commands : "git clone https://github.com/sigstore/rekor.git rekor-cli cd rekor-cli make rekor-cli cp rekor-cli /usr/local/bin/" rekor installs correctly and rekor-cli works fine.
> 
> am i missing some thing.

Typically it means `$GOBIN` is not in `$PATH`

**Comment by bobcallaway** [comment]
@Mohamed-AH please reopen if this is not a result of `$GOBIN` not being in your `$PATH`.
