### ISSUE TITLE
Genuine thought experiment

### ISSUE THREAD

**Issue by anoncam** [sigstore/rekor#1088]
Can rekor be run at the edge and use something like workers.dev and a data store to enhance resiliency as scale is achieved?   Serverless rekor?? @Cloudflare

**Comment by dlorenc** [comment]
Rekor itself is stateless, and trillian is mostly stateless, so yes-ish? You just need the data storage system. Trillian doesn't support SQLite but that's probably what it would take to work on Cloudflare.

**Comment by anoncam** [comment]
perfect.

[i think there a few ways](https://developers.cloudflare.com/workers/learning/using-durable-objects/)

**Comment by anoncam** [comment]
> Rekor itself is stateless, and trillian is mostly stateless, so yes-ish? You just need the data storage system. Trillian doesn't support SQLite but that's probably what it would take to work on Cloudflare.

https://developers.cloudflare.com/workers/tutorials/query-postgres-from-workers-using-database-connectors/

**Comment by znewman01** [comment]
Very interesting idea.

FWIW the performance bottlenecks that we run into in Rekor don't seem to be addressed by horizontal scaling. Rather, the main issues are (1) superlinear scaling for transparency logs: the billionth entry takes longer to process than the millionth, and (2) the requirements for strict serialization order in a shared backing datastore that can't handle partitioning. Even so, the [sharding](https://docs.sigstore.dev/rekor/sharding/) we've done seems to get us where we need to be.

Are you interested in pursuing this? Do you see a specific need? If not, I'm inclined to close this out until there is such a need.

**Comment by znewman01** [comment]
I'm going to close this for now. If you have a specific need or want to work on this, comment and we can reopen!

**Comment by anoncam** [comment]
> I'm going to close this for now. If you have a specific need or want to work on this, comment and we can reopen!

yeah let me get cloudflare in this. I would like to offer worker for platforms to the sigstore community at my cost, let's see what we can build.
