### ISSUE TITLE
Add public key method to EntryImpl

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#1173]
**Description**

This would be useful for getting an entry's public key or certificate without having to first cast the entry body to a specific type.

**Comment by asraa** [comment]
I'm personally in favor of this, and even a `Signature()` public method. 

I think having this content easily accessible will make it easy for clients to grab (at least for Go). Signature also seems useful to me in case (I personally hope), the SET scopes down further to just Signature content.
