### ISSUE TITLE
How does Rekor search work

### ISSUE THREAD

**Issue by toddysm** [sigstore/rekor#1209]
**Question**
I am trying to figure out how to search for records in Rekor. Finding a record by UUID, log index, and email is OK but more advanced searches find nothing for me. I tried searching by image name, and image SHA and got nothing. Are those searches available? It does seem so from the help on the Rekor CLI.

```
$ rekor-cli search --artifact 562077019569.dkr.ecr.us-west-2.amazonaws.com/flasksample
Error: invalid argument "562077019569.dkr.ecr.us-west-2.amazonaws.com/flasksample" for "--artifact" flag: Key: '' Error:Field validation for '' failed on the 'url' tag
$ rekor-cli search --sha sha256:9bd049b6b470118cc6a02d58595b86107407c9e288c0d556ce342ea8acbafdf4
no matching entries found
$ rekor-cli search --sha 9bd049b6b470118cc6a02d58595b86107407c9e288c0d556ce342ea8acbafdf4
no matching entries found
```

**Comment by Hayden-IO** [comment]
If you're still having issues, I'd ask on the #rekor Slack channel.
