### ISSUE TITLE
openpgp dependency is deprecated

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#1211]
**Description**

The currently used openpgp library is no longer supported by golang. We should find another library that is (protonmail -https://github.com/ProtonMail/go-crypto - is likely the best choice, as [keybase](https://github.com/keybase/go-crypto) seems to no longer be updated).

cc @lukehinds

**Comment by asraa** [comment]
Is it this issue? https://github.com/sigstore/rekor/issues/286

**Comment by Hayden-IO** [comment]
Yep, closing as duplicate
