### ISSUE TITLE
Ρεκόρ meaning.

### ISSUE THREAD

**Issue by geoah** [sigstore/rekor#125]
Fist of all can I just say that the project looks really interesting and I'm looking forward to playing around with it.

---

Mostly just FYI: The word Ρεκόρ in Greek translates to something like "previous conduct/performance/high value" or "track record", rather than what I assume you were going for in naming the project. And it would be used in terms such as "world record", "in record time", "set a new record". (https://www.wordreference.com/gren/%CF%81%CE%B5%CE%BA%CF%8C%CF%81)

Still a cool name though :)

**Comment by lukehinds** [comment]
@geoah , we actually need to pivot to a new name, do you have any ideas on some other funky greek names that sound good / look good when spelled out in English?
