### ISSUE TITLE
EntryImpl.Verifier only returns a single public key, but should support returning multiple keys

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/rekor#1278]
**Description**

intoto envelopes support multiple signatures with potentially multiple unique public keys, so Verifier should return `[]pki.PublicKey` instead of a single one

@haydentherapper

**Comment by Hayden-IO** [comment]
SG, I’ll take a look at this. Going to do some refactoring to make it easier to know what key type you’re working with too.
