### ISSUE TITLE
Support other KMS keys besides GCP

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#1324]
**Description**

Very trivial change, we just need to update https://github.com/sigstore/rekor/blob/a90366e15d837d1e33c04797119ffff8b63a12ff/pkg/signer/signer.go#L27 to load all KMS providers and fetch the key with `kms.Get` ([fulcio example](https://github.com/sigstore/fulcio/blob/main/pkg/ca/kmsca/kmsca.go#L42))

**Comment by jbgcarnes** [comment]
This feature would help me for sure. If the project open to an MR about it?

**Comment by Hayden-IO** [comment]
Feel free to fix this issue, thanks! It should be straightforward.

**Comment by bobcallaway** [comment]
This will have a pretty dramatic increase in the dependency footprint for Rekor, but the fix is pretty straightforward.

**Comment by jtcarnes** [comment]
Sorry, family health crisis. Taken care of now. I'll push it out in a week or so.
