### ISSUE TITLE
Add instrumentation to the servers

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#134]
I poked around a bit and it appears we have two main options for metrics: Prometheus and OpenCensus. Trillian appears to support both as well: https://github.com/google/trillian/blob/master/monitoring/prometheus/metrics.go

Here's what I'm hoping to get:

- Cloud-agnostic instrumentation code. The code should only know about the metrics we need to expose, not where they're going.
- Minimal operational complexity
- Since we're running on GKE now, it would be nice for the metrics to show up in the Stackdriver console.

With Prometheus, we would expose metrics on a /metrics endpoint. Then, a Prometheus server would scrape those metrics and upload to Stackdriver.

With OpenCensus, we would use a Stackdriver exporter directly from the Rekor code. This is a bit too direct of a coupling for my liking, but the exporter can be configured to point anywhere easily. I think using this is probably our best bet to avoid having to run a separate Prometheus service.

If we ever have to move off of GKE, we can swap out a few lines to export to wherever we want.

**Comment by axelsimon** [comment]
As i was telling @lukehinds recently, i've been meaning to get to know Prometheus better, and from a first go at playing with it i'd be happy to take this one on.

If i understand correctly, @dlorenc, with the OpenCensus option we have an exporter running in the Rekor code and exporting the metrics to either directly Stackdriver, or to an arbitrary endpoint which an instance of Prometheus could then scrape?
I'm not quite clear what you mean by a separate Prometheus instance, in that context. Simply that this avoids us having to run a Prometheus instance at all, as the metrics are directly exported into Stackdriver, but that when/if we move off GKE we can easily have the metrics exported to a given endpoint and _then_ have a Prometheus do the job of monitoring?

**Comment by dlorenc** [comment]
> I'm not quite clear what you mean by a separate Prometheus instance, in that context. Simply that this avoids us having to run a Prometheus instance at all, as the metrics are directly exported into Stackdriver, but that when/if we move off GKE we can easily have the metrics exported to a given endpoint and _then_ have a Prometheus do the job of monitoring?

Exactly! With OpenCensus we can export directly from the Rekor process to Stackdriver/AWS/Azure/whatever, or to an HTTP endpoint (served from the same process) that a Prometheus server would then scrape.

I haven't actually gotten very far here, and I'm not an expert, so I might be misunderstanding things too.

**Comment by dlorenc** [comment]
https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/358 might be of use.

**Comment by Hayden-IO** [comment]
Completed as part of productionization/1.0 release
