### ISSUE TITLE
A little help to understand and how to solve error and warning messages at the rekor-server container

### ISSUE THREAD

**Issue by edson-morais-os** [sigstore/rekor#1382]
**Question**

Summarizing my context:
* I'm deploying Sigstor Rekor by using the Helm chart [Rekor] version [1.2.0].
* I'm using MariaDB and Redis from a cloud vendor.
* All of this deployment is using Terraform.
* The components (Trillian LogSigner, Trilliian LogServer, and Rekor Server are up)

**My Concerns**
* Accessing all pods/containers to verify the deployment results I noticed the points below:

[Pod = rekor-server | Container = rekor-server]

1 - Message: app/root.go:114 pprof enabled false
2 - Message: could not discover absolute path: stat .: permission denied
3 - Message: warning: could not resolve current working directory: stat .: permission denied

As I didn't find any information related to these messages/'behaviors' in the Sigstore Helm Charts documentation, please, could you help me to understand the reason for that?

I really appreciate any tips :)

Thank you so much.
"Edinho"
 
![image](https://user-images.githubusercontent.com/76122453/224952233-b2122d34-554a-4a25-97da-7b77eb2b0e8e.png)

**Comment by bobcallaway** [comment]
For (1) - this is just used if a developer wants to turn on [profiling](https://github.com/google/pprof) of rekor (configured via command line option seen at https://github.com/sigstore/rekor/blob/8993091a4b78548bc77211cd268a65793a7e2761/cmd/rekor-server/app/root.go#L74) 

(2) looks like an error potentially coming from spf13/viper, and (3) looks like an error from go-openapi/spec - but without knowing the full k8s config I don't have any ideas.

**Comment by edson-morais-os** [comment]
Thank you so much, Mr @bobcallaway .

Please, do you have some idea about what the K8S config items (2) and (3) are related to?
... Authentication level? Container user? Namespace Roles?

**Comment by edson-morais-os** [comment]
Hi Guys!

Just to share! The reason for the Rekor container errors below:

2 - Message: could not discover absolute path: stat .: permission denied
3 - Message: warning: could not resolve current working directory: stat .: permission denied

Is that the default value [ ?.securityContext.runAsUser = 65533 ] don't exist in the container.

After attaching the container and executing [ cat /etc/passwd ] was possible to see the nonrootuser [ 65532 ].
