### ISSUE TITLE
On board CNCF projects

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#144]
Seek to make an accetable proposal to onboard some CNCF projects into rekor.

- [ ] Select candidate projects from teh CNCF eco-system
- [ ] Outline a process of how they can start to sign and store rekor manifests into rekors transparency log with automation and ease of use as key.
- [ ] Outline a process of how users can then benefit from the signed manifests to attest the inetgrity of release downloads.
- [ ] Implement the above proposal into the selected CNCF candidate projects.

**Comment by idvoretskyi** [comment]
@dlorenc @bobcallaway please go ahead and apply on LFX Mentorship platform - https://mentorship.lfx.linuxfoundation.org/project/8ffde3ac-79a5-4715-8d4d-10f2ce952536, unfortunately, I was unable to add you directly.

**Comment by me-diru** [comment]
Hello @lukehinds, @bobcallaway 

I am interested in mentorship opportunity under this project, May I know where to get started and how to communicate further?
I wasn't able to find any slack group/channel and any particular issues so far.

Thank you

**Comment by lukehinds** [comment]
@diru1100 I am not sure how the application part works, @idvoretskyi is there are process interns should follow to apply for this?

**Comment by me-diru** [comment]
> I am not sure how the application part works

@lukehinds 
Mentees should apply here: https://mentorship.lfx.linuxfoundation.org/project/8ffde3ac-79a5-4715-8d4d-10f2ce952536

For application, one must submit a cover letter and resume. 

I am interested in this project, but I am new to this. So any guidance/resources on what you are looking for and what should be done would help a lot to get started and eventually apply for the opportunity.

**Comment by imskr** [comment]
Hi, @lukehinds I've submitted the cover letter and resume. How to join the community in slack?

**Comment by arnav-t** [comment]
Is there a Slack, Gitter, or an IRC channel for Project Rekor?

**Comment by SantamRC** [comment]
Hey @lukehinds , I am interested to contribute to this project. Is there any pre-requisite along with submitting the cover letter and resume?

**Comment by justaugustus** [comment]
Kubernetes xref: https://github.com/kubernetes/release/issues/1837
(I'll have the Kubernetes [Release Managers](https://github.com/kubernetes/sig-release/blob/master/release-managers.md) group investigating this quarter.)
