### ISSUE TITLE
docs: rekor-cli `go install` directions broken

### ISSUE THREAD

**Issue by spencerschrock** [sigstore/rekor#1440]
**Description**

The instructions at https://docs.sigstore.dev/rekor/installation/#using-go-install are out-of-date as `go install` is incompatible with the replace directive added in #1272

https://github.com/golang/go/issues/44840#issuecomment-792789581
```
go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest
go: github.com/sigstore/rekor/cmd/rekor-cli@latest (in github.com/sigstore/rekor@v1.1.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**What should the correct behavior be?**

I would expect the documented installation options to work, or a note explaining the problem if it's expected to be temporary.

**Version**

N/A

**Comment by Hayden-IO** [comment]
cc @AdamKorcz - It looks like this is caused by https://github.com/sigstore/rekor/blob/fb50ad8043d7efa161333e96928172ee0cb78adf/go.mod#L148. Do you know if we can remove this or if you can upstream your changes?
