### ISSUE TITLE
Idea: Timestamping Authorities

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#147]
Rekor sort of acts as a timestamp witness today. A rekor entry can be returned with the timestamp at which it was included in our log. This requires that the user trust rekor's clocktime, though.

RFC3161 outlines Timestamping authorities. There is a go client here: https://github.com/digitorus/timestamp

A timestamping authority is a service that uses X.509 certificates to sign a timestamp along with an opaque payload. This signature can be used as a third-party time attestation. 

**Meta Part**: The timestamp attestation is signed. Rekor stores signatures. Rekor could store its own timestamp signatures, to act as a self-proof of time accuracy. From time to time, Rekor would generate a payload with it's own observed time and get it signed by one (or more) timestamp authorities.

The public key for this authority, the payload, and the signature form a Rekor entry, which could then be stored in Rekor itself.

**Comment by dlorenc** [comment]
This could run as a separate service on a cron. Every day, or hour? The service would:

- Take the latest STH and timestamp from the rekor log
- Pack that up into some structure
- Send that off to a TSA using RFC3161. Example: https://github.com/digitorus/timestamp/blob/master/timestamp_example_test.go#L19
- Turn the resulting signature and certificate into a RekorEntry
- Upload that to the log

**Comment by lukehinds** [comment]
what do you see as some of the beneficiary use cases from this Dan?

**Comment by dlorenc** [comment]
Anyone using certs with expiration to sign artifacts. They need some mechanism to attest that the signature happened while the cert was valid.

Third party systems do this today, but we can do it as part of rekor automatically.

**Comment by rektide** [comment]
> Meta Part: The timestamp attestation is signed. Rekor stores signatures. Rekor could store its own timestamp signatures, to act as a self-proof of time accuracy. From time to time, Rekor would generate a payload with it's own observed time and get it signed by one (or more) timestamp authorities.

This reminds me a little bit of PublicTimestamp.org . Anyone could submit hashes for content they have, which would be put into the current Public Timestamp Block (PTB). Every 15 minutes a new block would get made, which would start with a hash of the just-finished block's content. In this way each block certified the last. As far as I know they didn't go out to any external timestamp authorities to get attestation, but they asked the community to help attestation by publishing the most recent PTB's hashes periodically in public places. I had a couple tweets & G+ posts where I'd leave the most current PTB hashes.

Side note, Public Timestamp was/is also a Linux Foundation (OSDL) project!!!!!!!! Time is a flat circle!

**Comment by dlorenc** [comment]
Hah - thanks for the pointer! That does sound very similar to our goal here.

**Comment by asraa** [comment]
> Anyone using certs with expiration to sign artifacts. They need some mechanism to attest that the signature happened while the cert was valid.


Do you envision adding timestamp verification as being integrated into signature verification flows (like cosign)? I don't see much value in adding timestamp attestations if it's not easy to check them. E.g.

`COSIGN_EXPERIMENTAL=1 cosign verify -key cosign.pub -verify-timestamp <authority public key> dlorenc/demo `

would
* Verify the artifact exists in rekor
* Verify that the signature was integrated in the log before the cert expired
* Verify that the integrated time falls within the timeframes attested by the authority public key (or some default)

**Comment by dlorenc** [comment]
> `COSIGN_EXPERIMENTAL=1 cosign verify -key cosign.pub -verify-timestamp <authority public key> dlorenc/demo `
> 
> would
> 
> * Verify the artifact exists in rekor
> * Verify that the signature was integrated in the log before the cert expired
> * Verify that the integrated time falls within the timeframes attested by the authority public key (or some default)

Hah, this is out of date a bit. It's already integrated into cosign: https://github.com/sigstore/cosign/blob/main/KEYLESS.md#usage

**Comment by asraa** [comment]
> Hah, this is out of date a bit. It's already integrated into cosign: https://github.com/sigstore/cosign/blob/main/KEYLESS.md#usage

Oops! Nice. Sorry this was proposing the additional step of verifying rekor's timestamp against a timestamp authority.

**Comment by dlorenc** [comment]
Ahhh yeah we can probably strengthen this up a few different ways!

**Comment by Hayden-IO** [comment]
Closing as this was added, then removed, then will be added back :)

**Comment by rektide** [comment]
How where when was tinestanp authorities ever added back?

**Comment by Hayden-IO** [comment]
This was split into its own service - https://github.com/sigstore/timestamp-authority
