### ISSUE TITLE
Rekor signature validity

### ISSUE THREAD

**Issue by desh-woes** [sigstore/rekor#1517]
**Question**
Right now, it is unclear to me how long the rekor public key will remain valid. 

It is possible to obtain the public key via Rekor's API [https://rekor.sigstore.dev/api/v1/log/publicKey](https://www.google.com/url?q=https://rekor.sigstore.dev/api/v1/log/publicKey&sa=D&source=docs&ust=1685541680620741&usg=AOvVaw3mKIlJf2ynHnahfwcDBuso). This allows one to store this public key for offline verification of Rekor log entries. 

But if this key changes, then the offline rekor log entries would be invalidated (I am assuming). Are there plans to change the rekor public key? What conditions could trigger this change? And what happens to previously downloaded rekor log entries? Would they need to be updated since they will be signed by the new key pair? or will I need to keep track of the previous keys? 

What's the mechanism here? Please let me know if my question is unclear.

**Comment by Hayden-IO** [comment]
See https://dlorenc.medium.com/using-the-update-framework-in-sigstore-dc393cfe6b52 - for the public instance of Sigstore, we distribute the root of trust for the Sigstore services using TUF. Cosign and other Sigstore clients are configured to use the TUF root to get public keys for Rekor.
