### ISSUE TITLE
rekor cli upload with cosign public key

### ISSUE THREAD

**Issue by chunteck** [sigstore/rekor#1573]
I know that by using `cosign sign-blob`, it will automatically upload an entry into rekor tlog, but I was experimenting with uploading the record to the rekor tlog manually (using rekor-cli), and it seems to encounter an issue with the cosign public key. Is the cosign public key not in the correct format for rekor-cli to use?

```
cosign generate-key-pair

 // intentionally not uploading to rekor
cosign sign-blob --key cosign.key --output-signature sig.txt --tlog-upload=false artifact.txt

// i tried the different pki formats but all did not work
rekor-cli upload --public-key cosign.pub --signature sig.txt --artifact artifact.txt --pki-format tuf|pgp|minisign|ssh|x509|pkcs7

```

**Comment by Hayden-IO** [comment]
`--pki-format` should be `x509` when uploading a public key.

**Comment by lkatalin** [comment]
This seems related to an issue I am finding also. Using `--pki-format x509`, I'm not able to successfully upload with `rekor-cli upload` (although using `cosign verify-blob` with the same material does work):

```
[lily@fedora cosign]$ cosign verify-blob --key keys/cosign.pub --signature blob_sig generated_payload --insecure-ignore-tlog=true
WARNING: Skipping tlog verification is an insecure practice that lacks of transparency and auditability verification for the blob.
Verified OK

[lily@fedora cosign]$ rekor-cli upload --artifact generated_payload --public-key keys/cosign.pub --pki-format x509 --signature blob_sig
error: error retrieving external entities: invalid signature when validating ASN.1 encoded signature
```

Why do these two commands have different results?

**Comment by Hayden-IO** [comment]
Responding on the other issue about signature formats.
