### ISSUE TITLE
Add redis auth

### ISSUE THREAD

**Issue by ianhundere** [sigstore/rekor#1613]
**Description**

Would y'all be open to a PR that enables redis auth? I've never used golang, but it looks fairly straightforward to implement using the [options struct](https://github.com/go-session/redis/blob/4e7f0dcd632c5ada68449f4fedcc806ef66e52ce/options.go#L13).

**Comment by Hayden-IO** [comment]
Yes, feel free to open a PR, thanks!

**Comment by ianhundere** [comment]
oops, sorry for muddying the waters. feel free to delete that extra PR. 😅
