### ISSUE TITLE
How to verify signatures in public Rekor

### ISSUE THREAD

**Issue by mdavid01** [sigstore/rekor#1665]
**Question**
Hi team:  I want to verify the signature for the alpine image shown @ https://hub.docker.com/layers/library/alpine/latest/images/sha256-c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33?context=explore.  I am able to curl to public rekor and find uuids.  I am able to 'cosign verify' my companies' registry images.  I've tried many cosign verify parameter combinations for the public rekor but no luck.  The command always returns:
`**Warning** Missing fallback target fulcio.crt.pem, skipping
**Warning** Missing fallback target fulcio_intermediate_v1.crt.pem, skipping
Error: no matching signatures
main.go:69: error during command execution: no matching signatures`

Pls provide, or point me to doc'n with, a working 'cosign verify' command for the alpine image.  If it helps, the docker pull command is 'docker pull alpine'.  If, by chance, the result above is correct, please choose an alternate image so I can see a working 'cosign verify' example using the public rekor.

Thanks.
Michael

**Comment by Hayden-IO** [comment]
Take a look at https://docs.sigstore.dev/verifying/verify/. If you have more questions, please post on Sigstore's cosign slack channel.

I would also double check that Alpine has a Sigstore signature attached. https://docs.sigstore.dev/signing/signing_with_containers/ has documentation for signing containers.
