### ISSUE TITLE
Rekor publicKey issue on kubernetes (private Sigstore)

### ISSUE THREAD

**Issue by VikramPunnam** [sigstore/rekor#1799]
I've completed the configuration of the private Sigstore within the Kubernetes environment by following the instructions provided in the following link: https://github.com/sigstore/helm-charts.

However, when my Rekor pod undergoes a restart, it results in a change of the publicKey. Consequently, this necessitates an update in the tuf-system namespace and the need to restart the Kyverno controller on the Kubernetes.

Is there a solution to maintain a static/custom publicKey, preventing it from changing when the Rekor pod is restarted?

**Comment by bobcallaway** [comment]
Don't use the in-memory signer - you should be using KMS or a file based signer instead

https://github.com/sigstore/rekor/blob/16e232301b744ab8ee3d2fa9147d62704e9a0355/cmd/rekor-server/app/root.go#L99C36-L99C49

**Comment by Hayden-IO** [comment]
You'll need to set `server.signer` in the helm chart to either `awskms://keyname`, `azurekms://keyname`, `gcpkms://keyname`, or `hashivault://key`. You can also use the filename of the private key for a file-based signer, but the helm chart will need to be updated to add the file password (I'm doing that now).
