### ISSUE TITLE
Can we use S3 Bucket for Rekor attestation storage

### ISSUE THREAD

**Issue by VikramPunnam** [sigstore/rekor#1839]
Hi,

I have deployed and set up the Sigstore on the private Kubernetes environment.
I have used Mysql and KMS for the database and signing keys.

I would like to use the S3 as a Rekor attestation storage.

I have configured like below. but getting an error as shown below.

bucket: s3://sigstore-rekor

**Configuring attestation storage at s3://sigstore-rekor
42
2023-11-20T15:22:33.378Z	PANIC	api/api.go:173	open blob.Bucket: no driver registered for "s3" for URL "s3://sigstore-rekor"; available schemes: file, gs, mem
41
github.com/sigstore/rekor/pkg/api.ConfigureAPI**

How can I configure S3? Please let me know..

**Comment by bobcallaway** [comment]
I don't have an easy way to test this, but #1844 should fix this.

**Comment by cpanato** [comment]
We might want to setup some e2e tests with minio

**Comment by bobcallaway** [comment]
could also potentially do with localstack
