### ISSUE TITLE
pubsub/bigquery

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#191]
We could make some other types of (UNTRUSTED) feeds available to simplify integrations.

* All entries could get sent to a public pubsub/kafka topic for others to use.
* All entries could get synced to a public bigquery instance for ad-hoc querying/analysis.
* Publish daily/hourly (signed) snapshots and backups of the log to some kind of CDN.

**Comment by Hayden-IO** [comment]
We chatted about this issue today. As more clients are interested in monitoring Rekor, we'll need to figure out how to scale reads for Rekor. One option is read replicas. Pub/sub is another good option.

cc @flxw

**Comment by Hayden-IO** [comment]
This is complete.
