### ISSUE TITLE
500 from /api/v1/log/proof if lastSize > log size

### ISSUE THREAD

**Issue by phad** [sigstore/rekor#199]
`curl -v "https://api.rekor.dev/api/v1/log/proof?lastSize=1255"` gives response:
```
{"code":500,"message":"Unexpected result from transparency log"}
```

when `treeSize` is 1254:

`curl -v "https://api.rekor.dev/api/v1/log"` gives response:
```
{"rootHash":"294ed76b6e1f8f17ef81732fa63d0e09d2c51b367f5f23f56fd0f914ab2c38ff","signedTreeHead":{"keyHint":"Ni+Oy6cvQyY=","logRoot":"AAEAAAAAAAAE5iApTtdrbh+PF++Bcy+mPQ4J0sUbNn9fI/Vv0PkUqyw4/xZrB2iBGKEpAAAAAAAACNYAAA==","signature":"MEQCIAh9SkSMSNdlCUIDTi4SX5c9p/G0jIjD3fvI4FpXEcgqAiA4c7zYi27yRchoBdKSCcHM3cB9N45Rc9Xx+adEvQF1PA=="},"treeSize":1254}
```

but gives a 200 response when `lastSize` = `treeSize`:

`curl -v "https://api.rekor.dev/api/v1/log/proof?lastSize=1254"`

```
{"hashes":["073970a07c978b7a9ff15b69fe15d87dfb58fd5756086e3d1fb671c2d0bd95c0", *snip*,
"da8602de4650d2a53862a65d3035204d96bcd7e25377574ff437249ab092bd5d"],"rootHash":"294ed76b6e1f8f17ef81732fa63d0e09d2c51b367f5f23f56fd0f914ab2c38ff"}
```

**Comment by bobcallaway** [comment]
Thanks for the issue @phad - were you expecting a 400 Bad Request response instead of the 500 error?

**Comment by phad** [comment]
Hey @bobcallaway - yes, I thought a 400 error would be more appropriate, since the cause is poorly chosen parameters being sent by the client, and not a fault on the server side.

**Comment by phad** [comment]
An alternative approach is that taken by Google's CT logs based on trillian.
The equivalent API in CT is `/ct/v1/get-sth-consistency` with params `first` and `second`.
If `second` > `treeSize` it seems to be just clipped to `treeSize` and HTTP 200 is returned.
