### ISSUE TITLE
client loginfo: prints unauthenticated root hash and tree size

### ISSUE THREAD

**Issue by rgdd** [sigstore/rekor#200]
The root hash and tree size that is printed by the client command `loginfo` is prepared here:

https://github.com/sigstore/rekor/blob/3c6ce1678a9b4e02e98be671fe901490d071fcb8/cmd/cli/app/log_info.go#L71

As far as I can tell that output is unauthenticated because it is not connected to the signed log root which is verified here:

https://github.com/sigstore/rekor/blob/3c6ce1678a9b4e02e98be671fe901490d071fcb8/cmd/cli/app/log_info.go#L115

**Comment by bobcallaway** [comment]
@rgdd take a look and see if #201 addresses your concern here. Thanks for the issue!

**Comment by rgdd** [comment]
@bobcallaway yup, looks good to me!
