### ISSUE TITLE
config rekor.yaml confusion

### ISSUE THREAD

**Issue by rurban** [sigstore/rekor#202]
The docs at https://sigstore.dev/get_started/client/ point at `~/.rekor/rekor.yaml` for the default yaml.
The code at `cmd/cli/app/root.go` leaves config empty (I've added the path above), and the help points to `$HOME/.rekor.yaml`
state is stored in the `.rekor` dir, so the docs would be right, I think.

I would find it useful to store my public-key, oops public_key url there

**Comment by lukehinds** [comment]
I will close this as the old site is not in use anymore
