### ISSUE TITLE
Failed to upload an gzipped artifact

### ISSUE THREAD

**Issue by shizhMSFT** [sigstore/rekor#208]
Following https://sigstore.dev/get_started/client/, I have the following output
```
$ gpg --armor -u jdoe@example.com --output mysignature.asc --detach-sig myrelease.tar.gz
$ rekor upload --rekor_server http://localhost:3000 --signature mysignature.asc --public-key mypublickey.key --artifact "http://localhost:8000/myrelease.tar.gz"
2021/03/12 07:41:27 error retrieving external entities: openpgp: invalid signature: hash tag doesn't match
```

The reason why `hash tag doesn't match` is that the signature is for the payload `myrelease.tar.gz` not for its decompressed content. However, the rekor cli decompress the content automatically and then do the verification.

**Comment by dlorenc** [comment]
Thanks @shizhMSFT ! This should be deployed now.
