### ISSUE TITLE
Document mirror setups

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#211]
There might be a few already we can pull from in the Trillian examples. It could be as simple as a bash for loop that tails one log with `rekor-cli loginfo` and `rekor-cli get --uuid`, then uploads those entries to another `Rekor` server instance.

Ref #210

**Comment by dlorenc** [comment]
We should also document some easy to use "non-transparent" mirrors for internal use. We're planning to throw data into bigquery/pubsub as part of #191. We should document how others can slurp in data directly from the log (and verify it!) then stick it into something queryable/indexable for internal use.

**Comment by Hayden-IO** [comment]
Closing - We don't have any mirrors in the ecosystem and instead would distribute new logs rather than view-only mirrors in a TUF root.
