### ISSUE TITLE
Consider storing the full x509 Certificate

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#215]
When an entry is added with an x509 certificate instead of a public key, we strip the cert and only store the public key bytes.

The CT Log stores the full cert, but we can only search it by timestamp or full cert, not public key.

If we store the full cert in rekor, we can more easily perform joins between the logs and discovery of certs.

Downsides to storing the full cert:

- More data, more changes for bad content making it into the log
- Duplication of signatures (we could end up with entries for the public key and the cert)

Other ideas:
- Store both! Add one entry for the cert and one for the public key. This might be confusing though.
- Only store certs if they were issued by fulcio, otherwise store the public key.

I think right now I prefer storing the whole thing...

**Comment by OR13** [comment]
Might be worth elaborating on the use cases a bit more on the issue.

I think the main benefit of having the full cert is for forensic / incident response teams tracing upstream issues no?

It seems like facilitating discovery and relationship mapping is worth the extra bytes, and redundancy can be handled with clever UI / labeling.

**Comment by dlorenc** [comment]
FYI, we ended up going forward with this, your summary of the tradeoffs is basically exactly why!
