### ISSUE TITLE
Incorrect dependency version in v1.2.2 go.mod

### ISSUE THREAD

**Issue by airycanon** [sigstore/rekor#2159]
**Description**

The package at https://github.com/sigstore/rekor/blob/v1.2.2/go.mod#L54 references a non-existent version. 
Please visit https://github.com/AdamKorcz/go-fuzz-headers-1/commit/e936619f9f18 using the commit `e936619f9f18`, which states: 
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

**Version**

v1.2.2

**Comment by Hayden-IO** [comment]
@AdamKorcz Can we switch to https://github.com/AdaLogics/go-fuzz-headers, will you be upstreaming the changes in your fork?

**Comment by Hayden-IO** [comment]
Closing - newer versions should not have this issue.
