### ISSUE TITLE
Add option to enable TLS for communication with Trillian

### ISSUE THREAD

**Issue by fghanmi** [sigstore/rekor#2163]
**Description**
Currently, the communication between Rekor and Trillian server does not support Transport Layer Security. This exposes the system to potential security risks such as data interception and man-in-the-middle attacks. To enhance the security and integrity of services communications, it is imperative to introduce an option to enable TLS - Rekor would ensure the verification of Trillian's certificates.

**Comment by bobcallaway** [comment]
I think this is complete now?
