### ISSUE TITLE
Entries getting added to TreeHead table even if Rekor APIs are not invoked

### ISSUE THREAD

**Issue by subhamoycomputer** [sigstore/rekor#2169]
Hi All,

once we bring up Rekor in our local system, we have seen one unusual behavior. Even though the APIs are not in use, still there are entries getting added to the “TreeHead” table constantly at random periodic intervals. It is hecause of this behavior the data count in TreeHead table is constantly increasing.
Is this a known behaviour? Can this be stopped by setting any flags on startup commands ?

**Comment by bobcallaway** [comment]
I'd recommend filing this question on the google/trillian repo since this is a Trillian question
