### ISSUE TITLE
Bug: Request entity too large

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#220]
I hit this when trying to upload a 3.7M artifact using the --artifact flag. It worked for me when passing in a URL. I think a reasonable limit makes sense here, but 3.7M seems like it should work. Not sure where to fix this.

**Comment by dlorenc** [comment]
Ooh, apparently we can use DEBUG=1 to trace these!

```
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
```

so it's actually coming from our ingress.

**Comment by asraa** [comment]
Looks like this is fixed with a max of 32 mb.

Do we want to catch the error earlier?

**Comment by dlorenc** [comment]
Ah good call, yeah we could keep this open to track erroring earlier in the client.

We can also bump this up higher if we want.

**Comment by bobcallaway** [comment]
reopening per discussion at https://github.com/sigstore/rekor/pull/264#discussion_r612716174

**Comment by bobcallaway** [comment]
Rekor service now correctly formats this error message and is handled correctly by rekor-cli 

`[POST /api/v1/log/entries][413] createLogEntry default  &{Code:413 Message:Request Entity Too Large}`
