### ISSUE TITLE
Does createtree command needs to be executed during every restart of Rekor services ?

### ISSUE THREAD

**Issue by subhamoycomputer** [sigstore/rekor#2205]
Is the “createtree” command need to be executed every time we start Rekor services ?
We setup Rekor for the first time in our server and ran the commands for Trillian log server, Trillian log signer, Createtree and Rekor server. Question is - whenever we restart our servers do we need to run createtree command every time or is it required only for the first time run ?

**Comment by bobcallaway** [comment]
only first time. once the treeID is known, you should pass it into the rekor-server command via config/command line args.
