### ISSUE TITLE
Data duplication in MySQL DB

### ISSUE THREAD

**Issue by subhamoycomputer** [sigstore/rekor#2227]
We have setup Rekor in 2 VMs. In VM-1, Rekor is connecting to MySQL instance 1 and in another VM (VM-2) its connecting to MySQL instance 2. Data replication constantly takes places between these 2 MySQL Instances.

Issue is - today we got 1 request coming in VM-1 at Sept 17 2024 11:16:21.300 AM and in another VM-2 request came at Sept 17 2024 11:16:21.295 AM. Its because of this, replication broke in both the instances because the Sequence Number from SequencedLeafData is same for both the rows.

Is there a way we can acert this situation by passing any extra arguments at startup ?

**Comment by Hayden-IO** [comment]
Replication is likely not possible because of this exact issue. You need leader election, which trillian supports, for the log signer - there must be only one instance that sequences entries.
