### ISSUE TITLE
Update Rekor API after get by UUID removal

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#229]
Looks like the GetLeavesByHash call got removed somewhere, our CI running against the trillian_log_server at head broke. I pinned it, but we'll need to fix that before we can update

**Comment by lukehinds** [comment]
I asked in the trillian slack why they removed this. It seems to be because they are not using it in CT:

https://github.com/google/trillian/pull/2243

**Comment by bobcallaway** [comment]
FYI for switching to a different API call: 

https://github.com/sigstore/rekor/blob/e0c5e30da866c9691eb0a8fcae3dc17edec5bff6/pkg/api/entries.go#L149

**Comment by dlorenc** [comment]
To summarize, we'll need to change up the API a bit here. Get by UUID doesn't really make sense, if you have the UUID you'll instead want to verify.

**Comment by dlorenc** [comment]
Let's use this to track the API changes/simplifications we'll make here as a result of the trillian changes.
