### ISSUE TITLE
Proposal: Add an RFC3161 Timestamp server to our API

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#232]
This would ease integration with Java and other tooling that expects timestamps in this format. We could expose two APIs:

- A normal RFC3161 variant, where users send us a TSR and we reply with a timestamp
- A less difficult to use one, where users just send us a blob and we return a timestamp, in the RFC3161 format.

Both variants would log signatures to Rekor, and could include the index in the response.

**Comment by dlorenc** [comment]
This gets a lot easier with #262

**Comment by dlorenc** [comment]
@bobcallaway - does this help with your maven plugin at all? I know java expects timestamps.

**Comment by dlorenc** [comment]
https://blog.cyborch.com/trusted-time/ for reference on what a more "usable" rfc3161 could look like :)

**Comment by bobcallaway** [comment]
> @bobcallaway - does this help with your maven plugin at all? I know java expects timestamps.

I think it could, but need to think more about the sequencing of all of this.

**Comment by Hayden-IO** [comment]
Closing - A timestamp authority was once implemented in rekor, then removed, and reimplemented in https://github.com/sigstore/timestamp-authority
