### ISSUE TITLE
garbled text in error message

### ISSUE THREAD

**Issue by ahmetb** [sigstore/rekor#233]
making request to https://api.rekor.dev/api/v1/log/entries/retrieve

with body:

<details>
<summary>click to show</summary>
<pre>
{
    "entries": [
        {
            "apiVersion": "0.0.1",
            "kind": "rekord",
            "spec": {
                "data": {
                    "content": "eyJDcml0aWNhbCI6eyJJZGVudGl0eSI6eyJkb2NrZXItcmVmZXJlbmNlIjoiIn0sIkltYWdlIjp7IkRvY2tlci1tYW5pZmVzdC1kaWdlc3QiOiJzaGEyNTY6MmI3MjFiYjFjNDZlYTYxOGU5NzZiNzAxYTc5ZGU0NWMzNTEzZWM0MWFhMmY0Mzg2YWQ1YTc4YzFhMzZkMTY1OCJ9LCJUeXBlIjoiY29zaWduIGNvbnRhaW5ldiBzaWduYXR1cmUifSwiT3B0aW9uYWwiOnsiazEiOiJ2MSJ9fQ=="
                },
                "signature": {
                    "content": "MEQCIGV/WmeH9wdf0HYpnDbAgXZIQDDCTk30VU1vjAGaTIdxAiBvrfJ7vf0yv4mQB+GkX5N7Lx0BKkDWBmod0fF69m0rwg==",
                    "publicKey": {
                        "content":"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUUFobFpjR0Z6M1REYXVXbmVQTDlwNHkxYVFOZApUYmxFQ1F2dElwY3dGTTJ2czh6Q01GYkFXWUdOakJBbDlSY2pCOXhVZ2k4dEZrejRuRGtUaXVSRmFBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
                    },
                    "format":"x509"
                }
            }
        }
    ]
}
</pre>
</details>

getting response

```
{
  "code": 500,
  "message": "signature mismatch for 0D\u0002 eZg��\u0007_�v)�6��vH@0�NM�UMo�\u0001�L�q\u0002 o��{��2���\u0007��_�{/\u001d\u0001*@�\u0006j\u001d��z�m+�"
}
```

which seems less than desirable. intentional?

**Comment by bobcallaway** [comment]
@ahmetb  certainly not intentional... will have to dig further
