### ISSUE TITLE
Serve a fulcio signed certificate of the rekor public key

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/rekor#256]
In cosign we're currently working on bundling all necessary proofs into the signature (https://github.com/sigstore/cosign/issues/181) -- the idea is that we can verify the signature is in rekor without having to actually access the rekor tlog.

Ideally, we would like cosign to verify these signatures with as few public keys required as possible. Instead of having to store rekor's public key in the code, we could:
1. Create a fulcio signed cert that contains the rekor public key
2. Store that cert in the cosign signature

That way we can get rekor's public key, but only have to trust the fulcio root CA to get it from the cert.

I was planning to create the cert, and then making it accessible from the rekor API in the same way the rekor public key is currently accessible.

**Comment by dlorenc** [comment]
+1! We can add it onto the API here: https://github.com/sigstore/rekor/blob/main/pkg/api/tlog.go#L122

When we get the certificate signed.

**Comment by priyawadhwa** [comment]
Opted to store the public key in cosign instead, so this is no longer needed!
