### ISSUE TITLE
Figure out code coverage

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#269]
I don't think we need to really track this continuously, but it would be nice to have a manual way to see an accurate coverage representation.

It's pretty easy to see unit test coverage:

```shell
go test -v -coverpkg=./... -coverprofile=profile.cov ./...
go tool cover -html profile.cov
```

but the majority of our coverage here is actually at the e2e level. We lose coverage tracking there because the tests are spun up in a different process and we exercise the command line/API for that.

**Comment by Hayden-IO** [comment]
Codecov was added
