### ISSUE TITLE
Admin tooling for redis index

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#270]
**Description**

It would be great to have some tooling to automatically rebuild the redis index in case it gets behind the log or we drop entries. Right now we index whenever entries are added, but if something gets dropped it would never be added.

A manual tool we can run would be great as a start, then figure out some way to run it continuously (maybe a goroutine/cron in the same server process? maybe a separate cron in the cluster?)

**Comment by Hayden-IO** [comment]
I think we're good to close this now that https://github.com/sigstore/rekor/tree/main/cmd/backfill-redis has been implemented.
