### ISSUE TITLE
Use JWKS format for public keys

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/rekor#271]
We could consider using the JWKS format for the rekor public keys, which would be useful if we want to send multiple keys to a user. This could be nice to have once we start rotating keys, so that users can figure out which public key they need to verify against based on some provided timestamp.

Related comment: https://github.com/sigstore/rekor/pull/267#discussion_r613193322

**Comment by Hayden-IO** [comment]
@priyawadhwa Is this something you think we should still consider, given we have a stable format now?

**Comment by priyawadhwa** [comment]
Nope I think this can be closed
