### ISSUE TITLE
Dump out url when debug flag is set

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#280]
In order for us to get some better insight during adoption phases, we could have a debug flag `REKOK_DMP=1` which dumps the artefact URL to a file or if its a locally sourced artifact, the name of the file and mimetype.

This would give us some idea on what is being signed to get an idea on adoption / use.

**Comment by Hayden-IO** [comment]
Closing since it's been awhile, feel free to reopen if you think this is still needed
