### ISSUE TITLE
Does the rekor server validates the artifact?

### ISSUE THREAD

**Issue by hhurtado** [sigstore/rekor#284]
I've been reading the documentation at https://sigstore.dev/get_started/client/ and https://sigstore.dev/get_started/server/ and the first one states that the client validates the signature for the artifact but, does the rekor server validates the signature before creating the entry in the transparency log?

I don's see a specific error response for this case in the openapi.yaml file neither the code that makes this validation.

Thanks in advance

**Comment by bobcallaway** [comment]
The verification is done in a type-specific manner (see https://github.com/sigstore/rekor/blob/4d98f80a4907314f3d1f641abb956d4996731bf3/pkg/types/rekord/v0.0.1/entry.go#L265 for the generic Rekord type), but see https://github.com/sigstore/rekor/blob/4d98f80a4907314f3d1f641abb956d4996731bf3/pkg/api/entries.go#L106 for where an HTTP 400 Bad Request error is returned if the input content is malformed or the signature cannot be verified.

Let me know if this doesn't answer your question. Thanks!

**Comment by hhurtado** [comment]
Hi,

This is just what I was looking for, thank you very much
