### ISSUE TITLE
Rekor CLI distribution

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#32]
Once #29 is complete and we are happy with  an initial implementation, we should think about how developers get the tool. 

One method is `go get`.

Another is to release right here on github (and of course make an entry into the tlog)

OS Dist packaging (allow `dnf install rekor` or `pacman rekor` etc).

* Fedora
* Debian
* Arch Linux

**Comment by dlorenc** [comment]
+1 on doing a real release, with a real entry in the tlog.

**Comment by LeSuisse** [comment]
Just so you know, I have opened PRs to include rekor and cosign in nixpkgs:
https://github.com/NixOS/nixpkgs/pull/117805
https://github.com/NixOS/nixpkgs/pull/117812 + https://github.com/NixOS/nixpkgs/pull/117976

It also looks like `rekor-cli` is available on Arch Linux via `community`: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rekor
