### ISSUE TITLE
Temporal Log Sharding

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#353]
We need to plan a way to shard out the log by time. CT logs typically start fresh every year, and require users to fetch entries from the correct log by knowing when the certificate was issued.

We could do this easily - but it might be nice to think through an API server that aggregates multiple logs, to allow for querying across a range of them. A frozen log is still useful, artifacts run for many years. It becomes easier to publish the entire year as a frozen merkle tree, and querying can even become easier with multiple verifiable maps built up on different indices.

**Comment by dlorenc** [comment]
Ref #352

**Comment by dlorenc** [comment]
High level ideas:

We could maintain a (signed) shard map, which specifies:

- The root hash for each log
- Which index ranges belong to each log

When you query by index, we can easily look up the correct log using these ranges
When you query by UUID, there should be at most one log with the right entry. How can we make sure of this? Should we iterate through all the logs?

**Comment by lkatalin** [comment]
I'm adding @dlorenc 's comments from #433 here to keep it all in one place:

Up next:
- support starting the server with multiple log IDs, instead of just one.
   - this will probably look like a config file containing a map of index ranges to log ids.
    - only one can be "active"
- support parsing the UUID during GET calls to determine which log to query (with defaulting for the 0 case here)


Also related: #352 
Also related: #255

**Comment by dlorenc** [comment]
Also see: https://github.com/sigstore/rekor/issues/487

**Comment by lkatalin** [comment]
>       * this will probably look like a config file containing a map of index ranges to log ids.

Do we still want a config file, since we have [code in place](https://github.com/sigstore/rekor/blob/main/pkg/sharding/ranges.go) that does this mapping?

**Comment by lkatalin** [comment]
Related:
#629 #630 #631 #632

**Comment by Hayden-IO** [comment]
Logs are sharded!
