### ISSUE TITLE
"go get" for the cli is returning an error code

### ISSUE THREAD

**Issue by sylvestre** [sigstore/rekor#355]
Even if the build works after this, the command:
```
go get -u -t -v github.com/sigstore/rekor/cmd/rekor-cli
echo $?
```
is returning 1 (while it should return 0)

I haven't seen any error in the log

Please note that I don't know much about go, so, it might just be me :)

**Comment by dlorenc** [comment]
Which go version are you using?

**Comment by sylvestre** [comment]
The one coming from Debian: go1.15.9
