### ISSUE TITLE
"rekor upload --artifact <file>" should accept only URL (or improve the error message)

### ISSUE THREAD

**Issue by sylvestre** [sigstore/rekor#363]
The doc  ( https://sigstore.dev/get_started/client/ ) says
`"The upload command sends [...] artifact URL to the rekor transparency log."`
and
`"download a local copy of the artifact"`
but the client help talks about "path" too
`      --artifact fileOrURLFlag     path or URL to artifact file`

Maybe it works when the server is local too but trying with a remote server, the error message is cryptic:

```
$ rekor upload --rekor_server https://rekor.sigstore.dev --signature mysignature.asc  --public-key /tmp/a.key --artifact llvm-toolchain-snapshot_13~++20210709100617+3e97d11df8ce.orig.tar.xz
2021/07/10 10:13:21 &{0 } (*models.Error) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface
```

For other playing with rekor, following command works:

```
$ rekor upload --rekor_server https://rekor.sigstore.dev --signature mysignature.asc  --public-key /tmp/a.key --artifact https://apt.llvm.org/unstable/pool/main/l/llvm-toolchain-snapshot/llvm-toolchain-snapshot_13\~%2b%2b20210709100617%2b3e97d11df8ce.orig.tar.xz
Created entry at index 5676, available at: https://rekor.sigstore.dev/api/v1/log/entries/0ecfb1505408258b60d0876fe831d27fcebac1b463a517f2a0c7ff8b83c2fb10
```

**Comment by bobcallaway** [comment]
@sylvestre thanks for the issue - specifying a local path OR a url should both work. The cryptic message isn't helpful (and we should improve that), but means that the server sent back an error that couldn't be parsed by the client.

could you re-run this with `DEBUG=1` and share the result? thanks!

**Comment by bobcallaway** [comment]
This may be a dup of https://github.com/sigstore/rekor/issues/220 if your file is > 32MB.

**Comment by sylvestre** [comment]
Yeah, it is about 90mb 
(sorry for the latency)

**Comment by bobcallaway** [comment]
I've updated the rekor service to return a correctly formatted error message:

`[POST /api/v1/log/entries][413] createLogEntry default  &{Code:413 Message:Request Entity Too Large}`
