### ISSUE TITLE
Work out release process for main -> release -> public instance

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#388]
We need to a method to firm up release procedures with the view of the public good instance. We should also look to have CI tests run against the current version of the public instance. I don't know how we would do this yet, but want to get it tracked as an item.

**Comment by lukehinds** [comment]
likely same for fulcio as well

**Comment by dlorenc** [comment]
Is this for the CLI/client? So basically test the client against the running version of the prod server?

**Comment by lukehinds** [comment]
> Is this for the CLI/client? So basically test the client against the running version of the prod server?

Yup!

Currently if someone pulls down 0.2.0 and aims it at the pub instance, it fails (just cutting a new release with @cpanato )

**Comment by dlorenc** [comment]
Yup, makes sense! Should be easy to add as a test matrix by changing the URL from a local instance to the prod one. We could even do the reverse combination (last released CLI against the service at HEAD)

**Comment by Hayden-IO** [comment]
Closing as we have this issue in the p-g-i repo
