### ISSUE TITLE
Plugable Types

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#40]
This is a placeholder to scope out plugable types. At present we have the following generic manifest type:

```
{
    "URL": "",
    "SHA": "",
    "PublicKey": "",
    "Signature": ""
}
```

My proposal is that we add a namespace.

```
{
	"type": "rekord",
	"version": "0.1",
	"spec": "https://github.com/projectrekor/rekor/rekord_spec.txt",
	"body": {
		"URL": "https://example/release/my_release.tar.gz",
		"SHA": "83jfj8we89903uhejw88…",
		"PublicKey": "PUBLIC_KEY",
		"Signature": "SIGNATURE"
	}
}
```

* note: I am sure the above can be improved and open to suggestions. I wanted to get the initial intent scoped out.

`ns` will then map to a type in `rekor/pkg/types/rekord.go` which in turn will have its own validation checks, version control, signing library (gpg etc). 

I see this as work we should do sooner rather then later, to save us coupling too much to the current type and tooling. Changes should be minimal, so we can keep our existing work mostly intact - we will likely need some sort of parent parser who then marshalls the types to their mapped `types/<ns>.go`

@dlorenc @bobcallaway , please do share thoughts. I will expand this out over the next few days.

**Comment by bobcallaway** [comment]
Looking at https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.11.1 I'd prefer to mimic their behavior of having the client provide the schema reference in HTTP headers rather than modifying the object in the request body. 

If we do want to support other formats in the future, putting the schema reference into the body might end up colliding with their format. 

+1 to formalizing the rekord in a JSON schema document off of this repo. I do have thoughts on changing the rekord format which I described in https://docs.google.com/document/d/1Iy9TSGyUwfD6Ww5jro_V_pK8VEGNH_W7lYUT3B_4SDg/edit?usp=sharing

**Comment by lukehinds** [comment]
> Looking at https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.11.1 I'd prefer to mimic their behavior of having the client provide the schema reference in HTTP headers rather than modifying the object in the request body.
> 
> If we do want to support other formats in the future, putting the schema reference into the body might end up colliding with their format.
> 
> +1 to formalizing the rekord in a JSON schema document off of this repo. I do have thoughts on changing the rekord format which I described in https://docs.google.com/document/d/1Iy9TSGyUwfD6Ww5jro_V_pK8VEGNH_W7lYUT3B_4SDg/edit?usp=sharing

I need to update this, as I omitted to add that we should support beyond just json and include XML and YAML (we should be formatting agnostic). This way the likes of [SBOM](https://cyclonedx.org/#example-sbom) etc can make entries as well.

I might move this to a google doc and we can work it out there.

**Comment by dlorenc** [comment]
We discussed something like this in the meeting:

```json
{
	"type": "rekord",
	"version": "0.1",
	"spec": "https://github.com/projectrekor/rekor/rekord_spec.txt",
	"body": {
		"URL": "https://example/release/my_release.tar.gz",
		"SHA": "83jfj8we89903uhejw88…",
		"PublicKey": {
            "type": "minisign",
            "version": "v1",
            "body": {
                "signature": "foo"
            }
        },
        "Signature": "SIGNATURE",
        "ExtraData": {
            "type": "red-hat-extra-data",
            "version": "bar",
            "body": {
                "rpm-version": "foo",
                "compiler-version": "bar"
            }
        }
	}
}
```
