### ISSUE TITLE
Swagger link in readme doesn't work anymore

### ISSUE THREAD

**Issue by aapeliv** [sigstore/rekor#406]

**Comment by cpanato** [comment]
This refers to the link in this section: https://github.com/sigstore/rekor#api

@dlorenc @bobcallaway i never saw that before, we used to have that? we will continue serving this page or should we remove the link?

**Comment by lukehinds** [comment]
I heard @bobcallaway is willing to work on this.

**Comment by bobcallaway** [comment]
https://sigstore.github.io/swagger/?urls.primaryName=Rekor still works, but the fulcio openAPI definition is no longer working since it has been removed from that project.

**Comment by bobcallaway** [comment]
this is now fixed, closing
