### ISSUE TITLE
Using `rekor-cli verify` given just the --artifact and --public-key

### ISSUE THREAD

**Issue by kpcyrd** [sigstore/rekor#416]
**Description**

hi!

I'm trying to test a given text/artifact has been logged with a signature by a given public key:

```sh
$ rekor-cli verify --artifact commit.txt --pki-format=minisign --public-key <(echo RWTgyFZe5kun6ThArmRsxUKbmk8Wq32lpmBVLznM6OTyZBU/dV16vuzJ)
a detached signature must be provided
```

I'm wondering if it would be possible to do with just those two inputs if I don't care about a specific signature (as long as it's by the right keypair).

The following command works (although I'm not sure it's 100% safe to use):

```sh
$ rekor-cli verify --artifact commit.txt --pki-format=minisign \
    --public-key <(echo RWTgyFZe5kun6ThArmRsxUKbmk8Wq32lpmBVLznM6OTyZBU/dV16vuzJ) \
    --signature <(rekor-cli get --format json --uuid $(rekor-cli search --artifact commit.txt --pki-format=minisign \
        --public-key <(echo RWTgyFZe5kun6ThArmRsxUKbmk8Wq32lpmBVLznM6OTyZBU/dV16vuzJ) \
            | uniq -c | awk '{if ($1 == 2) print $2}' | tail -1) \
        | jq -r .Body.RekordObj.signature.content | base64 -d)
Current Root Hash: 2cb4359cc9b5e10c155236e91aa606b9cb3215546c59df23062f90d583439961
Entry Hash: dc20497cdddb5fdbcd42783c45a4cba49c34a62f5e9e89a1bbd78c0eaf8c17cd
Entry Index: 389317
Current Tree Size: 398433

Inclusion Proof:
[...]
```

It seems `rekor-cli search --artifact xxx --public-key yyy` is an `or` search, the combination of `uniq` and `awk` is an attempt to convert this into an `and` search.

I'm not sure how reasonable this use-case is, let me know what you think!

Thanks!

**Comment by bobcallaway** [comment]
> I'm wondering if it would be possible to do with just those two inputs if I don't care about a specific signature (as long as it's by the right keypair).

Not with the current implementation; in order to recreate the canonicalized entry, we need the artifact (or its digest), public key, and signature. The canonicalized entry can only be inserted once into the log, and its leaf hash (aka the entry UUID) is guaranteed to be unique in the log.

> 
> It seems `rekor-cli search --artifact xxx --public-key yyy` is an `or` search, the combination of `uniq` and `awk` is an attempt to convert this into an `and` search.
> 
> I'm not sure how reasonable this use-case is, let me know what you think!

Can you elaborate a bit more on the scenario (e.g. a developer signed an identical artifact multiple times (using the same key pair) and made entries into the tlog for all of the signatures)?

> 
> Thanks!

**Comment by kpcyrd** [comment]
> in order to recreate the canonicalized entry, we need the artifact (or its digest), public key, and signature.

Yes, if I got it right I'm basically executing two searches instead of a simple lookup.

> e.g. a developer signed an identical artifact multiple times (using the same key pair) and made entries into the tlog for all of the signatures

That's what I meant with "I don't care about a specific signature", any valid signature will do  :) The original command I posted didn't actually consider this case (fixed tjhis with `| tail -1`).

> Can you elaborate a bit more on the scenario

I'm attempting to use the public key as an append-only "namespace" in sigstore that I publish to, and the signature is only used to write to this namespace. This could be useful if I can't/don't want to distribute the signatures myself for some reason.

**Comment by asraa** [comment]
> It seems rekor-cli search --artifact xxx --public-key yyy is an or search, the combination of uniq and awk is an attempt to convert this into an and search.

I also want this! For the TUF types, I want someone to be able to search for the latest type of TUF metadata signed by a particular public key (root in TUF land). Then I could use `rekor verify --uuid blah` for the return value of the search

I think we had some ideas of exporting the data into bigquery to do more complex lookups like these (you'd still need to do a rekor verify though because the bigquery data isn't verifiable). Does that make sense for you?

**Comment by bobcallaway** [comment]
> I think we had some ideas of exporting the data into bigquery to do more complex lookups like these (you'd still need to do a rekor verify though because the bigquery data isn't verifiable). Does that make sense for you?

I'm a fan of that approach vs adding a ton of search/Boolean logic into rekor.

**Comment by kpcyrd** [comment]
It could be implemented in a `rekor-cli search-signatures` command that does two searches and lists intersections, but if there are either:

- a lot of signatures for this artifact
- a lot of signatures by this public key

this search could become expensive, so closing for now.

Thanks! :)
