### ISSUE TITLE
Release 1.0 planning

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#419]
Items needed for release 1.0

- [ ] Sharding process and API changes. #433 
- [ ] Documentation migrated / polished to docs.sigstore.dev
- [x] Rename Ecosystem to Origin in Checkpoints https://github.com/google/trillian-examples/pull/470 cc @bobcallaway 
- [ ] Serve and upload SignedTimestamp based on Checkpoints

**Comment by asraa** [comment]
Adding some
- [x] Rename Ecosystem to Origin in Checkpoints https://github.com/google/trillian-examples/pull/470 cc @bobcallaway 
- [ ] Serve and upload SignedTimestamp based on Checkpoints

**Comment by dlorenc** [comment]
Sharding stuff is ongoing! Ref #433

**Comment by cpanato** [comment]
I would like to add a cloudbuild + goreleaser when we release Rekor

then I have some questions:

1. We will use the same KMS key that we use to sign `cosign`? or we create another?
2. To push the data to the Rekor server how can we do that in an automated fashion way? there is any guide? or we just don't do it at this time?

@dlorenc @lukehinds @dekkagaijin

**Comment by cpanato** [comment]
And looks like we can review if we can make the v1.0.0 release soon, some PRs are already merged

**Comment by lukehinds** [comment]
I personally think we should be using keyless for signing as soon as we are ready. However we could use KMS as stop gap, if we can retro-sign previous releases using the fulcio root.

**Comment by naveensrinivasan** [comment]
This could be an issue https://github.com/sigstore/rekor/issues/481#issuecomment-966539148 unless the project restricts/recommends/documents the size of the upload for `1.0` IMO.
