### ISSUE TITLE
Implement Extra Data

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#44]
As per discussions on slack. Implement ExtraData for storing of the URL.

After downloading the artifact the URL will be parsed into ExtraData in the `addLeaf` function

```
leaf := &trillian.LogLeaf{
    LeafValue: byteValue,
    ExtraData: extraData,
}
```

**Comment by bobcallaway** [comment]
I'd propose we add a timestamp (in UTC) to the ExtraData object as well.

**Comment by lukehinds** [comment]
Second to this issue is @dlorenc idea of logging two entries (one with url / one without). I prefer this myself.

**Comment by itewk** [comment]
was this implemented? im not seeing the url to the artifct that was signed being automatically added to extra data, which i thought is what this was saying it implemented.
