### ISSUE TITLE
Migrate docs to docs.sigstore.dev

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#444]
We now have a nice docs site, so let's start moving content into there.

Seeking volunteers to help with this and also add more content.

**Comment by doodzik** [comment]
@lukehinds I'm happy to help out on this one. Are you talking about moving the content from the readmes to the website?

**Comment by lukehinds** [comment]
hi @doodzik , yes, and that would be a great start. We will likely have to write some new material, but let's see what we have after a migration.
