### ISSUE TITLE
feat: Add rekor-cli to hombrew-core and gofish

### ISSUE THREAD

**Issue by dirien** [sigstore/rekor#457]
**Description**

Hi everyone,

it would be cool, if we could add the rekor-cli to the homebrew-core and gofish fish food repos. Similar to cosign.

I can help to do this if wanted.

**Comment by dirien** [comment]
Link #419 and #443 to this issue.

**Comment by cpanato** [comment]
hello @dirien 
rekor-cli is already in homebrew, you can install that using

```shell
brew tap sigstore/tap
brew install rekor-cli
```

for gofish lets see how cosign behaves and then we add that here as well :)

**Comment by dirien** [comment]
ahhh @cpanato, there is a own tap. I must have missed the parts in the doc!
