### ISSUE TITLE
Show counter of items in Rekor on rekor.sigstore.dev

### ISSUE THREAD

**Issue by imjasonh** [sigstore/rekor#466]
**Description**

Today, https://rekor.sigstore.dev is pretty sparse. It's basically just some basic HTML that more or less points to real docs on https://sigstore.dev.

What do people think about having a big ticker counting up the number of items in Rekor's tlog? It could query the current state on page load and just remain static, or it could even try to roughly deduce the rate of growth and animate the counter with some kind of rolling or [split flap display](https://www.oatfoundry.com/split-flap/) like at an olde-timey train station. Here's a snippet to display that in JavaScript for example: https://codepen.io/broregard/pen/LNroXL

**Comment by mattmoor** [comment]
I miss the 90s too, Jason 😉
