### ISSUE TITLE
Swagger link from README is 404

### ISSUE THREAD

**Issue by imjasonh** [sigstore/rekor#467]
**Description**

https://github.com/sigstore/rekor#api says:

> API
> If you're interesting in integration with Rekor, we have an [OpenAPI swagger editor](https://sigstore.dev/swagger/)

https://sigstore.dev/swagger/ is a 404 for me 💥

<img width="321" alt="Screen Shot 2021-10-26 at 5 03 31 PM" src="https://user-images.githubusercontent.com/210737/138960593-3ce97980-4fdc-4c09-ac25-cda3025b9054.png">

**Comment by bobcallaway** [comment]
duplicate of #406
