### ISSUE TITLE
Error out in case given file not found

### ISSUE THREAD

**Issue by Dentrax** [sigstore/rekor#486]
**Description**

Currently, the following error means that `checksums.txt` does not found in the current directory, which is a bit confused message to see what's going on actually:
```bash
$ rekor-cli search --artifact checksums.txt --sha 852dc7cfc62513324debede3cdc7a159843b7a05ae0eb740d905b074e4798d21
Error: invalid argument "checksums.txt" for "--artifact" flag: Key: '' Error:Field validation for '' failed on the 'url' tag
```

We can revise the error to smth like: `<FILE> does not found`

```bash
$ rekor-cli version
GitVersion:    v0.3.0
GitCommit:     e4303a87b92081e162e080ff69f36830c1035c09
GitTreeState:  clean
BuildDate:     '2021-07-28T08:08:56Z'
GoVersion:     go1.16.6
Compiler:      gc
Platform:      darwin/amd64
```

@developer-guy

**Comment by Hayden-IO** [comment]
This looks handled - https://github.com/sigstore/rekor/blob/main/cmd/rekor-cli/app/search.go#L128
