### ISSUE TITLE
go-playground/validator module is not imported with recommended URL

### ISSUE THREAD

**Issue by harryfallows** [sigstore/rekor#505]
go-playground/validator module is imported with its github.com URL (github.com/go-playground/validator) as opposed to its gopkg.in (gopkg.in/go-playground/validator.v9) URL. The go-playground/validator [README](https://github.com/go-playground/validator/tree/v9.31.0) suggests importing it with its gopkg.in URL (gopkg.in/go-playground/validator.v9), and other projects follow this notation (e.g. [gin-gonic/gin](https://github.com/gin-gonic/gin/blob/v1.5.0/go.mod)). This can be fixed by changing the URL where the module is imported.

**Comment by dlorenc** [comment]
I think this has been fixed, thanks!
