### ISSUE TITLE
Propose asraa as maintainer

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#536]
@sigstore/rekor-codeowners 

I would like to propose @asraa be promoted to a maintainer. Asra has done some solid work in rekor and is highly a valued contributor.

**Comment by cpanato** [comment]
+1

**Comment by asraa** [comment]
I would definitely be happy to step up to triage issues and review PRs!

**Comment by dlorenc** [comment]
+1!

**Comment by bobcallaway** [comment]
+1 - Congratulations @asraa and thanks for all the hard work! :)

**Comment by justaugustus** [comment]
Asra rocks!!!

**Comment by puerco** [comment]
+10000

**Comment by inferno-chromium** [comment]
Amazing work Asra!
