### ISSUE TITLE
Trillian database containers are not built on arm

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#545]
We could send some patches upstream, or build these ourselves. We don't really need them to come from upstream, it's just convenience. It's not even clear they intend for these to be used directly:

https://github.com/sigstore/rekor/blob/main/docker-compose.yml#L48

**Comment by Hayden-IO** [comment]
This seems outdated, and we currently use a trillian instance that is built and signed from sigstore maintainers
