### ISSUE TITLE
Question: How privacy-aware is querying right now?

### ISSUE THREAD

**Issue by mrueg** [sigstore/rekor#576]
Please feel free to correct, if I haven't gotten this right:
I assume, if a client queries the ledger to verify a signature e.g. for a specific signature of a package, the owner of the ledger can gain a lot of information about the client e.g.
* size of their infrastructure (e.g. number of distinct client requests from a specific ip range)  
* specific software possibly being used by clients (based on what signature got requested)
* specific version of software possibly being used by clients (based on what signature got requested and thus their vulnerabilities)

This could lead to a couple of things:
* the owner of the ledger has to be trusted to not log this request metadata
* or at least not use it with bad intentions 
* the ledger could become interesting for attacks with the main interest not altering the ledger but capturing those requests to gain information about potential targets.

A possible solution with the scope on client/server interaction (and neglecting the existence of anonymizing/pseudonymizing overlay networks) :
Instead of querying for a specific record, a client could possibly do some calculation to obfuscate the original intent and receive a couple of records from which the client selects the one they requested.

A simple but possibly inefficient solution could be:
Instead of querying for a specific uuid, the client could calculate hash(uuid)[0:n] and request the server to provide the number of records that match this request. If the data set is too big, the client would request hash(uuid)[0:n+1] until the set is satisfying the clients needs for privacy and size on what to transfer. Then the client would request those records.
Ideally this way it would force the owner of the ledger to serve all records and not allow them to hold some back.

**Comment by naveensrinivasan** [comment]
What you are asking is something like bitcoin/eth bloom filters for transaction privacy https://hackernoon.com/enhancing-bitcoins-transaction-privacy-with-bloom-filters-2m5q33ta , but instead for the rekor records. This is a valid request IMO.

**Comment by Hayden-IO** [comment]
I've found https://arxiv.org/pdf/2203.01661.pdf to be a really great paper that summarizes the various ways that Certificate Transparency has thought about how to address privacy concerns. It's not a solved problem unfortunately, there isn't a one size fits all solution.

Closing this since there's been no discussion in a year, feel free to reopen if you want to chat more!
