### ISSUE TITLE
Socks5 proxy support for rekor-cli

### ISSUE THREAD

**Issue by kpcyrd** [sigstore/rekor#590]
**Description**

I'd like to be able to set a socks5 proxy for requests made by `rekor-cli`. This would allow using `rekor-cli verify` through Tor.

Related to https://github.com/kpcyrd/pacman-bintrans/issues/21

**Comment by naveensrinivasan** [comment]
Would this work?

`HTTP_PROXY="socks5://127.0.0.1:1080/" rekor-cli verify`

>Recent versions of Go also have SOCKS5 proxy support via the HTTP_PROXY environment variable. You would write your http.Client code as usual, then just set the environment variable at runtime, for example:

https://stackoverflow.com/a/49580816/19407

**Comment by kpcyrd** [comment]
Setting `https_proxy="socks5://127.0.0.1:1080/"` worked, thanks!
