### ISSUE TITLE
Rekor API sometimes responds with YAML instead of JSON

### ISSUE THREAD

**Issue by imjasonh** [sigstore/rekor#593]
### To reproduce

1. Load https://rekor.sigstore.dev/api/v1/log/ in a browser (I'm using `Chrome 96.0.4664.55 (Official Build) (x86_64)`)
2. Reload until eventually the page will be downloaded as `download` (or `download (1)`, `(2)`, etc., if you keep reloading)

Looking at the Network tab in Chrome Devtools, it looks like response headers randomly change from `content-type: application/json;q=1` (no download) to `content-type: application/yaml` (download).

I'm not sure if this is hitting different backends that set the response `Content-Type` differently, but it's weird in any case.

You can also observe this using `curl`, and for other API methods:

```
$ curl -v https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462 2>&1 | grep yaml
$ curl -v https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462 2>&1 | grep yaml
$ curl -v https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462 2>&1 | grep yaml
< content-type: application/yaml
$ curl -v https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462 2>&1 | grep yaml
```

**Comment by bobcallaway** [comment]
yeah, i've seen this before as well and IIRC it comes down to a non-deterministic ordering of a map in one of our dependencies. I'll have to dig up the issue I filed (I hope!) upstream to link them together.

**Comment by imjasonh** [comment]
Oh wow, so it's not even just changing the content-type and returning JSON, it's changing the content between JSON and YAML:

```
$ curl https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462
{"e9e1b22f8a515824a6f6f05d193f02fdaf2baf38754659f2f0a992548a5b70a0":{"attestation":{},"body":"..."}}
$ curl https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462
e9e1b22f8a515824a6f6f05d193f02fdaf2baf38754659f2f0a992548a5b70a0:
  attestation: {}
  body: 
    ...
```

Any idea when this started happening? I haven't made a bunch of Rekor API calls since I hacked on #466 but I never saw this behavior then.

**Comment by imjasonh** [comment]
`curl -H "Accept: application/json" https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462`

and 

`curl -H "Accept: application/yaml" https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462`

both work as intended, and return JSON and YAML respectively.

**Comment by bobcallaway** [comment]
> Oh wow, so it's not even just changing the content-type and returning JSON, it's changing the content between JSON and YAML:
> 
> ```
> $ curl https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462
> {"e9e1b22f8a515824a6f6f05d193f02fdaf2baf38754659f2f0a992548a5b70a0":{"attestation":{},"body":"..."}}
> $ curl https://rekor.sigstore.dev/api/v1/log/entries\?logIndex\=1045462
> e9e1b22f8a515824a6f6f05d193f02fdaf2baf38754659f2f0a992548a5b70a0:
>   attestation: {}
>   body: 
>     ...
> ```
> 
> Any idea when this started happening? I haven't made a bunch of Rekor API calls since I hacked on #466 but I never saw this behavior then.

It's been months (if not longer). And technically the behavior is in spec since curl will default to set `Accept: */*` which means any response type is valid :/

**Comment by cpanato** [comment]
@bobcallaway @haydentherapper should we run a patch release?

**Comment by Hayden-IO** [comment]
That'd be great @cpanato, we'll want to test this out in staging to make sure there's no unintended side effects
