### ISSUE TITLE
CLI gives error message when creating hashedrekord types that isn't useful

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/rekor#604]
**Description**
```
bcallaway@bcallaway01:~/git/sigstore/rekor$ ./rekor-cli upload --signature /tmp/Qubes-R4.0.4-x86_64.iso.asc --artifact /tmp/Qubes-R4.0.4-x86_64.iso --public-key /tmp/qubes-release-4-signing-key.asc --type hashedrekord
invalid public key: failure decoding PEM
```

the `hashedrekord` type only supports X509 PKI at the moment, but this message doesn't help the user to understand that.

**Comment by asraa** [comment]
Ah, I see the other issue on this -- golang's openpgp didn't support verifying a hashed message, and is frozen, so unlikely to ever support signing/verifying hashed messages. 

Happy to fix the error message for now (EDIT: I see you have :D ). I see this is for https://github.com/sigstore/rekor/issues/601. I'm slightly hesitant to implement verification just given PGP problems but WDYT? Legitimate use case, and could be nice to have

**Comment by bobcallaway** [comment]
Unless we could use a supported PGP library to verify the signature via hash only, I think solving #601 by using `hashedrekord` won't work.
