### ISSUE TITLE
Standardize use of terminology re: UUID vs. EntryID

### ISSUE THREAD

**Issue by lkatalin** [sigstore/rekor#625]
This relates to the sharding work, ex. #487 . There are many places in the code that refer to a UUID. However, the new, longer UUID is called an "EntryID" and the UUID is only a component of this. Should we update references to `uuid` to be `entryID` where it refers now to this longer hex string? Alternatively, should we leave references to `uuid` alone but have a different term for the old (short) uuid?

There may also be a case for making sure `shardID`, `logID`, and `treeID` are merged into one term, though I haven't checked whether this is already the case. The new sharding package uses the term `treeID` based on the term in the log index work.

**Comment by Hayden-IO** [comment]
I think this is also complete, feel free to reopen if not
