### ISSUE TITLE
Trying to upload a signature created with minisign returns: failed to verify signature

### ISSUE THREAD

**Issue by p-** [sigstore/rekor#633]
Hello!

I'm trying to upload a signature created with minisign as described in [Signing and Uploading Other Types](https://github.com/sigstore/rekor/blob/main/types.md) using the official 0.4.0 build of the rekor-cli on linux (`rekor-cli-linux-amd64`).

I have created following sample to reproduce this error easily:
```
# Create new key
minisign -G -p ./mytest.pub -s ./mytest.key

# Sign file called test
minisign -s ./mytest.key -S -m test

# Upload with rekor-cli
rekor-cli-linux-amd64 upload --artifact test --signature test.minisig --pki-format=minisign --public-key=mytest.pub
```

Returns following error:
`[POST /api/v1/log/entries][400] createLogEntryBadRequest  &{Code:400 Message:Error processing entry: failed to verify signature}`

Maybe I've overlooked something, but from the error message it's not clear what it could be.

Sidenote:
Creating and uploading a PGP signature using the instructions described for [Rekor CLI](https://docs.sigstore.dev/rekor/CLI) did work.

**Comment by asraa** [comment]
This might be a problem with a difference of minisign versions. I'm testing this out with minisign 0.9 right now, that's what CI and e2e tests assume.

**Comment by asraa** [comment]
Yep! looks like that's it. It should work per the instructions with minisign 0.9. I'll try to dig into if there was a format change and make a backwards compat fix

Edit: this is because v.10 prehashes the input, it's an easy fix
