### ISSUE TITLE
Should providence.go file be renamed provenance.go?

### ISSUE THREAD

**Issue by jspeed-meyers** [sigstore/rekor#658]
**Description**

The file [here](https://github.com/sigstore/rekor/blob/main/pkg/types/helm/providence.go) is named providence.go 

Should its name actually be provenance.go?

I see that the struct created in the file is called `Provenance`.

I can put in a simple PR changing the file's name if changing the name is desirable.

**Comment by bobcallaway** [comment]
makes sense to me, tagging @sabre1041 to make sure that was a typo on his part

**Comment by asraa** [comment]
Fixed by https://github.com/sigstore/rekor/pull/758
