### ISSUE TITLE
Publish container images to Github container registry

### ISSUE THREAD

**Issue by nsmith5** [sigstore/rekor#681]
**Description**

Its a little tricky finding Rekor images right now. They do existing in GCR but aren't easy to discover. Having published and signed container images in GHCR will allow for them to be used in the public good instance and also by independent operators instead of building from source.

**Why Github container registry?**

I think github makes the images more easily discoverable for independent operators than google container registry. I'll file a ticket to publish rekor images there to so they match if folks think this is the right approach

**Comment by cpanato** [comment]
that should be straight forward to do, we can add that in the release pipeline as well
