### ISSUE TITLE
Rekor API: searching for an artifact using SHA256 fails if not prepended with `sha256:`

### ISSUE THREAD

**Issue by mbestavros** [sigstore/rekor#699]
The Rekor API returned no results for an artifact I'd just uploaded when I searched for it using its SHA. This is despite the record existing  and having the correct SHA (verified by searching using its pubkey).

@bobcallaway helped diagnose this; seems like the SHA needs to be prepended with `sha256:` to work, even though the [API spec](https://github.com/sigstore/rekor/blob/main/openapi.yaml#L546) does not explicitly require that.

**Comment by asraa** [comment]
Ah, nice catch. Do you have a reproducer I can use to test it out? We might just need to handle it in the server code here
https://github.com/sigstore/rekor/blob/97a5558f83d34c336ac383a846a777c32b8df6da/pkg/api/index.go#L40

and may be worth adding some additional verification, mimicing the search CLI  prefix check done here
https://github.com/sigstore/rekor/blob/c5a27911ad3ed1ff07773540dd918858af7077b9/cmd/rekor-cli/app/search.go#L116
