### ISSUE TITLE
Need to update state.json for new shards

### ISSUE THREAD

**Issue by lkatalin** [sigstore/rekor#713]
Otherwise, the output for `loginfo` is:

```
[rekor@fedora rekor]$ rekor-cli loginfo --rekor_server http://127.0.0.1:3000
current size of tree reported from server 1 is less than previously persisted state 19
```

**Comment by priyawadhwa** [comment]
We should have testing coverage for this! We can make sure this is working correctly by removing `--store_tree_state=false` from the e2e test in https://github.com/sigstore/rekor/pull/714/files
