### ISSUE TITLE
Production Rekor latency in excess of 750ms  frequently

### ISSUE THREAD

**Issue by nsmith5** [sigstore/rekor#741]
**Description**

The #alerts channel in sigstore frequently alerts on Rekor latency in excess of 750ms:

https://sigstore.slack.com/archives/C01P48SV8NQ

We should investigate the paths that lead to this latency and check if we can improve the situation. Perhaps pagination of the search endpoints?

**Comment by Hayden-IO** [comment]
Closing as outdated
