### ISSUE TITLE
https://www.sigstore.dev/swagger/  link is broken

### ISSUE THREAD

**Issue by aspear** [sigstore/rekor#797]
In the "API" section of  https://github.com/sigstore/rekor/blob/main/README.md, there is :

If you're interesting in integration with Rekor, we have an [OpenAPI swagger editor](https://sigstore.dev/swagger/)

At this moment, the https://sigstore.dev/swagger/ page is broken, it reports "/swagger not found"

(My apologies if this is the wrong place to report it, I figured that section of the site was likely generated from sources in this repo)

**Comment by eddiezane** [comment]
Let's track this at https://github.com/sigstore/rekor/issues/406.

**Comment by bobcallaway** [comment]
closing in deference to #406
