### ISSUE TITLE
Provide suite of tests for validating Rekor releases and deployments

### ISSUE THREAD

**Issue by k4leung4** [sigstore/rekor#841]
**Description**

To better streamline releases and deployments, we need a suite of tests that we can run to validate releases and deployments.

@priyawadhwa  Can you outline what tests you would like to see and what tests we have and which ones we are lacking.

**Comment by Hayden-IO** [comment]
cc @asraa

**Comment by priyawadhwa** [comment]
The [tests](https://github.com/sigstore/rekor/blob/main/tests/e2e_test.go) have pretty good coverage for uploading different types of objects (rekor, intoto attestation, jar etc), but it seems like they won't run against prod until it's updated to the latest version -- @k4leung4 will the new prod cluster be running v0.7.0?

Some manual tests we should run:
* Running the [prober](https://github.com/sigstore/scaffolding/tree/main/cmd/prober) on the command line: `go run ./cmd/prober --one-time` to check all read endpoints
* `cosign sign` and `cosign verify` on experimental mode to make sure adding an entry and finding an entry is working
* `rekor-cli loginfo` to check the length of the tree

**Comment by dlorenc** [comment]
Is this one fixed? I think the harness tests made it in and cover most of this.

**Comment by priyawadhwa** [comment]
Everything I mentioned in https://github.com/sigstore/rekor/issues/841#issuecomment-1142405342 is covered now by probers or tests. The harness tests also test adding/retrieiving entries across the most recent three server/CLI versions. Personally I think this can be closed.

cc @bobcallaway @asraa can we close this?

**Comment by dlorenc** [comment]
Closing, we can reopen or open new ones if we missed anything.

**Comment by dlorenc** [comment]
Bumping to blocker, but this has been fixed!
