### ISSUE TITLE
Format of attestation changed in rekor since v0.8.2

### ISSUE THREAD

**Issue by afrittoli** [sigstore/rekor#884]
**Description**

The `Attestation` used to be base64 encoded. We used to get parts of the attestation through:

```
rekor-cli get --uuid $REKOR_UUID --format json | jq -r .Attestation | base64 --decode | jq .<expression>
```

This script is now broken, so we changed it to

```
rekor-cli get --uuid \$REKOR_UUID --format json | jq -r .Attestation | jq .<expression>
```

**Version**

Rekor v0.8.2

**Additional info**

I have not seen any announcement in the release notes about this - I may have missed it though.
I just wanted to make sure that:
- the change was on purpose
- the change is announced in the release notes as it's a breaking change

**Comment by afrittoli** [comment]
https://github.com/tektoncd/plumbing/pull/1094

**Comment by dlorenc** [comment]
cc @bobcallaway

**Comment by bobcallaway** [comment]
This was mentioned in the PR https://github.com/sigstore/rekor/pull/769 but didn't make it into the release notes - I apologize for the omission. The change was on purpose though.
