### ISSUE TITLE
Index intoto attestations by email

### ISSUE THREAD

**Issue by imjasonh** [sigstore/rekor#890]
I've got a Rekor entry e305d5055749770fbfb067466f65d4879f77618f1263e29d78a350464af144db that contains an intoto attestation, which is signed by a Fulcio cert for 7577580991-compute@developer.gserviceaccount.com.

I can get the entry:

```
$ rekor-cli get --uuid e305d5055749770fbfb067466f65d4879f77618f1263e29d78a350464af144db
LogID: c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d
Attestation: {"_type":"intoto","predicateType":"tlogistry-fetched","subject":[{"name":"ghcr.io/distroless/static:latest-20220601","digest":{"sha256":"5663c7476101e26401b52a92d9b7adce6acd6036ebc330f0e60c828585e5e9c1"}}],"predicate":{"digest":"sha256:5b0dd45ad9a90361d4224850d73c8e0b9d87454772c13605ff6548f8ef88f4fa","tag":"ghcr.io/distroless/static:latest-20220601"}}
...
```

But I can't search by email and find the entry:

```
$ rekor-cli search --email 7577580991-compute@developer.gserviceaccount.com
no matching entries found
```

In Slack @bobcallaway seemed to indicate this was an oversight, and not intentional.

Filing a bug to track this. If someone can point me to the code where this happens I can try to make the change.

**Comment by asraa** [comment]
Thanks! This will be fixed by https://github.com/sigstore/rekor/pull/889
