### ISSUE TITLE
Improvements to rekor-cli verify command

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#891]
**Description**

* verify should verify a signed tree head (STH) signature
* verify should verify the STH signature uses the Rekor public key from TUF, not from the public key from the instance
* verify needs to be shard aware

**Comment by Hayden-IO** [comment]
cc @asraa

**Comment by var-sdk** [comment]
On making verify shard aware: verify uses search to find entries by index or uuid and that API also needs to be updated to be shard aware. See https://github.com/sigstore/rekor/issues/892.

**Comment by dlorenc** [comment]
Bumping to blocker

**Comment by asraa** [comment]
I'll take on verification of the root hash today
