### ISSUE TITLE
How can rekor prevent a record from a hacker?

### ISSUE THREAD

**Issue by kwang13** [sigstore/rekor#929]
If a hacker uses rekor-cli to upload a record of a public key/signature, how can an end user of rekor discover it?
Is there any user authentication mechanism that only authenticated user can upload records?
Or, will the rekor tell end user who uploaded the records when end user uses "get" or "verify"?
Thank you.

**Comment by Hayden-IO** [comment]
Check out https://docs.sigstore.dev/, this has more information on how to use the Rekor CLI and how users can query for artifacts in the log.
