### ISSUE TITLE
Proposal: Add Priya as a maintainer!

### ISSUE THREAD

**Issue by dlorenc** [sigstore/rekor#954]
**Description**

She's been one of the most active contributors over the last 3+ months: https://github.com/sigstore/rekor/commits?author=priyawadhwa, and landed significant major features including sharding.

I thought she was already a maintainer, but just realized she wasn't during the merge of https://github.com/sigstore/rekor/pull/945

**Comment by cpanato** [comment]
+1 <3

**Comment by asraa** [comment]
Very much in support!

**Comment by bobcallaway** [comment]
+1

**Comment by lkatalin** [comment]
+1 from me

**Comment by priyawadhwa** [comment]
thanks everyone!! :D

**Comment by lukehinds** [comment]
+1 congrats @priyawadhwa

**Comment by cpanato** [comment]
opened a PR to add @priyawadhwa to the @sigstore/rekor-codeowners 

https://github.com/sigstore/community/pull/85
