### ISSUE TITLE
api.SearchLogQueryHandler is not thread safe.

### ISSUE THREAD

**Issue by var-sdk** [sigstore/rekor#997]
**Description**

There are a couple of instances where slices are appended to inside of goroutines. e.g.

https://github.com/sigstore/rekor/blob/main/pkg/api/entries.go#L356

and 

https://github.com/sigstore/rekor/blob/main/pkg/api/entries.go#L356

Appends to slices are not thread-safe. Instead allocating the entire slice and assigning by index would work instead as in e.g.

https://github.com/sigstore/rekor/blob/main/pkg/api/entries.go#L356 

This would mean post-filtering nils to construct response payload.

**Version**

**Comment by cdris** [comment]
Can't assign myself, but I'll put in a pr for this.

**Comment by bobcallaway** [comment]
fixed by #1006
